apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-cont
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          ports:
            - containerPort: 8001
          env:
          - name: MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: db_host
          - name: KAFKA_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: kafka_host
          - name: FRONTEND_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: frontend_server
          - name: BACKEND_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: backend_server
          - name: API_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: api_server