apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-cont
        image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: kafka_host
        - name: FRONTEND_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: frontend_server
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: backend_server
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api_server